name: deploy-workflow-b

on:
  push:
    branches:
      - main
    paths:
      - apps/workflow-b/**
      - infra/workflow-b/**

jobs:
  deploy:
    permissions:
      contents: read
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      workflow_name: workflow-b
    secrets: inherit
